MarkoTell/Controllers/MarkoTellController.cs
using System.Collections.Generic;
using System.Net;
using MarkoTell.Dal;
using MarkoTell.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace MarkoTell.Controllers
{
    public class MarkoTellController : Controller
    {

        HomePageRepo repo = new HomePageRepo();
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public MarkoTellController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<AccountController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [Route("ModalForRegistration")]
        public ActionResult ModalForRegistration()
        {
            return PartialView("/Views/Partials/RegistrationModal.cshtml", repo.getCountries().FindAll(b=>b.Schools.Count > 0));
        }


        [Route("GetSchools")]
        [HttpGet]
        public ActionResult getSchools(int id)
        {
            var schools = repo.getCountries().Find(b => b.CountryID == id).Schools;

            List<Schools> model = new List<Schools>();
            foreach (var li in schools)
            {
                Schools b = new Schools();
                b.Adress = li.Adress;
                b.id = li.id;
                b.Name = li.Name;
                model.Add(b);
            }
   

            return Json(new
            {
                model
            });
        }



        [Route("MemberRegistration")]
        [HttpPost]
        public ActionResult MemberRegistration(ApplicationUser user)
        {
            user.UserName = user.Email;
            var result = _userManager.CreateAsync(user, user.password).Result;
            if (result.Succeeded)
            {
                _signInManager.SignInAsync(user, isPersistent: true);
                _signInManager.PasswordSignInAsync(user, user.password,true,false);
                return RedirectToAction("Index", "Home");
            }
            return View("");
        }
    }
}

MarkoTell/Views/Partials/RegistrationModal.cshtml
@model List<MarkoTell.Models.Countries>
@{ 
    var sch = Model[0].Schools;
}

<form action="/MemberRegistration" method="post" id="RegistrationForm">
    <div class="modal-body">
        <h4>Registracija</h4>
        <div class="input-group">
            <input name="Email" id="Email" class="form-control RegInput" required="" placeholder="Unesite Email/Korisničko ime" type="email">
            <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
        </div>


        <div class="input-group">
            <input id="password" pattern=".{5,}"   required title="8 characters minimum" name="password" class="form-control RegInput"  maxlength="10" placeholder="Unesite lozinku" type="password">
            <span class="input-group-addon"><i class="fa fa-eye fa-fw"></i></span>
        </div>

        <div class="input-group">
            <input id="name" name="name" class="form-control RegInput" required="" maxlength="50" placeholder="Ime " type="text">
            <span class="input-group-addon">
                <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
            </span>
        </div>

        <div class="input-group">
            <input id="surname" name="surname" class="form-control RegInput" required="" maxlength="50" placeholder="Prezime " type="text">
            <span class="input-group-addon">
                <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
            </span>
        </div>

        <div class="input-group">
            <input id="grade" name="department" class="form-control RegInput" required="" maxlength="1" placeholder="Unesite odjeljenje " type="text">
            <span class="input-group-addon">
                <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
            </span>
        </div>

        <div class="input-group">
            <input name="emailOfParents" id="emailOfParents" class="form-control RegInput" required="" maxlength="50" placeholder="Unesite Email roditelja" type="email">
            <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
        </div>



        <div class="input-group" required>
            <select name="contestCountry" id="contestCountry" onchange="getSchools(this)" class="RegInput">
                <optgroup label="Odaberite odjel">
                    @foreach (var li in Model)
                    {
                        <option value="@li.CountryID">@li.countryName</option>

                    }
                </optgroup>
            </select>
        </div>



        <div class="input-group">
            <select name="school" id="school" required class="RegInput">
                <optgroup label="Odaberite odjel" id="schoolsOptions">
                    @foreach (var li in sch)
                    {
                        <option value="@li.id">@li.Name</option>
                    }
                </optgroup>
            </select>
        </div>




        <div class="input-group" required>
            <select name="grade" class="RegInput">
                <optgroup label="Razred">
                    @for (int i = 1; i < 9; i++)
                    {
                        <option value="@i">@i</option>
                    }

                </optgroup>
            </select>
        </div>

        <div class="input-group">
            <select name="gender" required class="RegInput">
                <optgroup label="Spol">
                    <option value="M">M</option>
                    <option value="Z">Ž</option>
                </optgroup>
            </select>
        </div>

    </div>
    <div class="modal-footer">
        @*<button class="btn btn-default">Prijava <i class="fa fa-sign-in"></i></button>*@
        @*<input type="submit" class="btn btn-success" value="Potvrdi" onclick="ElementsSelected(event)" />*@
        <input type="submit" class="btn btn-success" value="Potvrdi"/>
        <button class="btn btn-danger" data-dismiss="modal" aria-label="Close">Zatvori<i class="fa fa-times" aria-hidden="true"></i></button>
    </div>
</form>

MarkoTell/Views/Partials/_footer.cshtml
<footer class="footer">
    <div class="wrapper-overfllow">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <div class="footer-left">
                        <div class="wrap">
                            <a href="index.html" class="foot-logo"><img src="images/amfootball/footer-logo.png" alt="footer-logo"></a>
                            <p>Activated charcoal trust fund ugh prism af, beard marfa air plant stumptown gastropub farm-to-table jianbing.</p>
                            <ul class="foot-left-menu">
                                <li><a href="staff.html">First team</a></li>
                                <li><a href="staff.html">Second team</a></li>
                                <li><a href="amateurs.html">Amateurs</a></li>
                                <li><a href="donations.html">Donation</a></li>
                                <li><a href="trophies.html">trophies</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12 col-lg-offset-1">
                    <div class="foot-news">
                        <h4>Recent news</h4>
                        <div class="item">
                            <a href="news.html" class="image"><img class="img-responsive" src="images/amfootball/foot-news-img.jpg" alt="news-image"></a>
                            <a href="news.html" class="name">When somersaulting Sanchez shouldered Mexico’s hopes</a>
                            <a href="news.html" class="date">25 Sep 2016</a>
                            <span class="separator">in</span>
                            <a href="news.html" class="category">Highlights</a>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-4 col-sm-12">
                    <div class="foot-contact">
                        <h4>Contact us</h4>
                        <ul class="contact-list">
                            <li><i class="fa fa-flag" aria-hidden="true"></i><span>276 Upper Parliament Street, Liverpool L8, Great Britain</span></li>
                            <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:team@email.com">team@email.com</a></li>
                            <li class="phone"><i class="fa fa-phone" aria-hidden="true"></i><span>+61 3 8376 6284</span></li>
                        </ul>
                        <ul class="socials">
                            <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-menu-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="footer-menu">
                        <li class="active"><a href="index.html"><span>Home</span></a></li>
                        <li><a href="matches.html"><span>Matches</span></a></li>
                        <li><a href="staff.html"><span>Team</span></a></li>
                        <li><a href="news.html"><span>News</span></a></li>
                        <li><a href="store.html"><span>Store</span></a></li>
                        <li><a href="contacts.html"><span>Contact</span></a></li>
                    </ul>
                    <a href="#top" class="foot-up"><span>up <i class="fa fa-caret-up" aria-hidden="true"></i></span></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <div class="copyrights">
                        © 2017 Team - Sport club psd template
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="created">
                        <a href="#">Created by <img src="images/common/created-icon.png" alt="create-by-image"> torbara</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



</footer>

MarkoTell/Views/Partials/_header.cshtml
<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-5 hidden-sm hidden-xs">
                <div class="top-contacts">
                    <ul class="socials">
                        <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                    <ul class="contacts">
                        <li class="phone"><i class="fa fa-phone-square" aria-hidden="true"></i>+61 3 8376 6284</li>
                        <li class="skype"><a href="callto:team.skype"><i class="fa fa-skype" aria-hidden="true"></i>team.skype</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-5">
                <div class="top-language">
                    <ul class="list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="images/common/en-flag.png" alt="selected language">EN</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#"><img src="images/common/fr-flag.png" alt="language">FR</a>
                                </li>
                                <li>
                                    <a href="#"><img src="images/common/en-flag.png" alt="language">EN</a>
                                </li>
                                <li>
                                    <a href="#"><img src="images/common/ru-flag.png" alt="language">RU</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                </div>
                <div class="top-search">
                    <form>
                        <input type="text" name="text">
                        <button><i class="fa fa-search" aria-hidden="true"></i></button>
                    </form>
                </div>
                <div class="clear"></div>
            </div>



            <div class="col-md-2 hidden-sm hidden-xs">
                <div class="MarkoTellUserHandle">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @:pozdrav @User.Identity.Name
                    <br />
                    }
                    <i class="fa fa-user-plus" aria-hidden="true" onclick="populateModalFromAjax('@this.Url.Action("ModalForRegistration", "MarkoTell")')"></i>
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                </div>
            </div>


        </div>
    </div>
</div>
<!--MAIN MENU WRAP BEGIN-->
<div class="main-menu-wrap sticky-menu">
    <div class="container">
        <a href="index.html" class="custom-logo-link"><img src="images/amfootball/logo.png" alt="logo" class="custom-logo"></a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#team-menu" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <nav class="navbar">
            <div class="collapse navbar-collapse" id="team-menu">
                <ul class="main-menu nav">
                    <li class="active">
                        <a href="index.html"><span>Home</span></a>
                        <ul>
                            <li><a href="amateurs.html"><span>Amateures Home</span></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="matches.html"><span>Matches</span></a>
                        <ul>
                            <li>
                                <a href="standing-cup.html"><span>Standings<i class="fa fa-long-arrow-right" aria-hidden="true"></i></span></a>
                                <ul>
                                    <li><a href="standings.html"><span>championship</span></a></li>
                                </ul>
                            </li>
                            <li><a href="club-stats.html"><span>club stats</span></a></li>
                            <li><a href="match-live.html"><span>match live</span></a></li>
                            <li><a href="broadcasts.html"><span>broadcasts</span></a></li>
                            <li><a href="upcoming-match.html"><span>upcoming match</span></a></li>
                            <li>
                                <a href="championships-archive.html"><span>championships archive<i class="fa fa-long-arrow-right" aria-hidden="true"></i></span></a>
                                <ul>
                                    <li><a href="championship.html"><span>championship information</span></a></li>
                                </ul>
                            </li>
                            <li><a href="live-text-stream.html"><span>Text stream</span></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="staff.html"><span>Team</span></a>
                        <ul>
                            <li><a href="player.html"><span>player first page</span></a></li>
                            <li><a href="player-second-page.html"><span>player second page</span></a></li>
                        </ul>
                    </li>
                    <li><a href="news.html"><span>News</span></a></li>
                    <li><a href="news-single.html"><span>News Single</span></a></li>
                    <li><a href="store.html"><span>Store</span></a></li>
                    <li><a href="contacts.html"><span>Contact</span></a></li>
                    <li>
                        <a href="#other"><span>other</span></a>
                        <ul>
                            <li><a href="404.html"><span>404</span></a></li>
                            <li><a href="offline.html"><span>offline</span></a></li>
                            <li><a href="coming-soon.html"><span>comming soon</span></a></li>
                            <li><a href="search.html"><span>search</span></a></li>
                            <li><a href="donations.html"><span>donations</span></a></li>
                            <li><a href="trophies.html"><span>trophies</span></a></li>
                            <li><a href="about-club.html"><span>about club</span></a></li>
                            <li><a href="checkout.html"><span>checkout</span></a></li>
                        </ul>
                    </li>
                    <li class="cart full">
                        <a href="#cart">
                            <span><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>
                        </a>
                        <div class="cart-drop">
                            <table class="ct">
                                <tr>
                                    <td class="delete"><a href="#"><i class="fa fa-close" aria-hidden="true"></i></a></td>
                                    <td class="info">
                                        <img class="product-image" src="images/common/cart-product.jpg" alt="product-image">
                                        <em>Men's T-Shirt<br><em class="price">1 x £ 60</em></em>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="delete"><a href="#"><i class="fa fa-close" aria-hidden="true"></i></a></td>
                                    <td class="info">
                                        <img class="product-image" src="images/common/cart-product.jpg" alt="product-image">
                                        <em>Men's T-Shirt<br><em class="price">1 x £ 60</em></em>
                                    </td>
                                </tr>
                            </table>
                            <div class="wrap">
                                <div class="total-text">Subtotal: </div>
                                <div class="total-digit">£ 120</div>
                            </div>
                            <div class="wrap btn-wrap">
                                <a href="cart.html" class="btn view">View cart</a>
                                <a href="checkout.html" class="btn check">checkout cart</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<!--MAIN MENU WRAP END-->